# Generated by Django 5.0.3 on 2024-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=65)),
                ("cidade", models.CharField(max_length=254)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
        ),
    ]
