# Generated by Django 5.0.3 on 2024-03-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/projetos/"
                    ),
                ),
                ("link_do_github", models.CharField(max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("filter-card", "Card"),
                            ("filter-app", "App"),
                            ("filter-web", "Web"),
                        ],
                        default="filter-web",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
