# Generated by Django 5.0.2 on 2024-03-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projeto", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "projetos",
                    models.ManyToManyField(
                        related_name="categorias", to="projeto.projeto"
                    ),
                ),
            ],
        ),
    ]
