# Generated by Django 5.0.3 on 2024-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="projetos",
            field=models.ManyToManyField(
                related_name="categorias", to="projeto.projeto"
            ),
        ),
    ]
