# Generated by Django 5.0.3 on 2024-03-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="projetos",
            new_name="posters",
        ),
    ]
