# Generated by Django 5.0.3 on 2024-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categoria", "0002_rename_projetos_categoria_posters"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="posters",
            field=models.ManyToManyField(
                blank=True, related_name="categorias", to="post.post"
            ),
        ),
    ]
